[phases.setup]
nixPkgs = ["python3", "unixODBC", "unixODBCDrivers.msodbcsql17"]

[phases.install]
cmds = ["python -m venv .venv", ". .venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = "python manage.py runserver 0.0.0.0:$PORT"